Repository HackSquadDev/discord-python, pull requests merged in 2022-10, with the labels that each got.

#11 Add docker
  .dockerignore
  Dockerfile
  hacksquad_discordpy/main.py
  requirements.txt
Labels: enhancement, hacktoberfest-accepted

#14 Create docker-image.yml
  .github/workflows/docker-image.yml
Labels: enhancement, hacktoberfest-accepted

#18 refactor: rewrote bot's core
  .editorconfig
  .env.example
  Dockerfile
  LICENSE
  README.md
  bot.py
  hacksquad_bot/__init__.py
  hacksquad_bot/cogs/hacksquad/__init__.py
  hacksquad_bot/cogs/hacksquad/core.py
  hacksquad_bot/internal_commands.py
  hacksquad_bot/main.py
  hacksquad_discordpy/main.py
  hacksquad_discordpy/objects/Team.py
  hacksquad_discordpy/objects/User.py
  hacksquad_discordpy/wrappers/constants.py
  hacksquad_discordpy/wrappers/leaderboard.py
  hacksquad_discordpy/wrappers/team.py
  poetry.lock
  pyproject.toml
  requirements.txt
  tests/__init__.py
  tests/test_hacksquad_discordpy.py
Labels: enhancement, hacktoberfest-accepted

#20 Add utils for requesting to API
  hacksquad_bot/utils.py
Labels: hacktoberfest-accepted

#21 feat: add linting workflows and pre-commit
  .github/workflows/black.yml
  .pre-commit-config.yaml
  bot.py
  hacksquad_bot/__init__.py
  hacksquad_bot/cogs/hacksquad/core.py
  hacksquad_bot/internal_commands.py
  hacksquad_bot/main.py
  hacksquad_bot/utils.py
  poetry.lock
  pyproject.toml
Labels: enhancement, hacktoberfest-accepted

#25 feat: loading & unloading cogs & more typing
  hacksquad_bot/internal_commands.py
  hacksquad_bot/main.py
  hacksquad_bot/utils.py
  poetry.lock
Labels: enhancement, hacktoberfest-accepted

#27 feat: caching API requests
  hacksquad_bot/cogs/hacksquad/utils.py
  hacksquad_bot/utils.py
  hacksquad_bot/utils/objects.py
  poetry.lock
  pyproject.toml
Labels: enhancement, hacktoberfest-accepted

#30 feat: leaderboard/team/search commands
  hacksquad_bot/cogs/hacksquad/core.py
  hacksquad_bot/cogs/hacksquad/utils.py
  hacksquad_bot/main.py
  poetry.lock
  pyproject.toml
Labels: enhancement, hacktoberfest-accepted

#29 hero and random hero commands
  hacksquad_bot/cogs/hacksquad/core.py
  hacksquad_bot/cogs/hacksquad/utils.py
Labels: enhancement, hacktoberfest-accepted

#31 feat: UI refresh + error handler
  .gitignore
  hacksquad_bot/cogs/hacksquad/core.py
  hacksquad_bot/cogs/hacksquad/utils.py
  poetry.lock
  pyproject.toml
Labels: enhancement, hacktoberfest-accepted

#35 Change from fork of discord.py to real repo
  hacksquad_bot/main.py
  poetry.lock
  pyproject.toml
Labels: bug, hacktoberfest-accepted

#34 Recommended Community Standards
  .github/workflows/ISSUE_TEMPLATE/bug_report.md
  .github/workflows/ISSUE_TEMPLATE/feature_request.md
  .github/workflows/pull_request_template.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
Labels: documentation, hacktoberfest-accepted

#43 Fix leaderboard from erroring if 51 is used
  hacksquad_bot/cogs/hacksquad/core.py
Labels: bug, hacktoberfest-accepted
